name: recognition_camera
version: 0.1.0
publish_to: 'none'
description: MVP for recognition_camera app

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5
  image_picker: ^1.0.7
  mobile_scanner: ^3.5.0
  tflite_flutter: ^0.12.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.4.0
  provider: ^6.1.1
  path_provider: ^2.1.2
  google_ml_kit: ^0.16.3
  flutter_localizations:
    sdk: flutter
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:

  uses-material-design: true
  assets:
    - assets/models/mobilenet_v1_1.0_224.tflite
    - assets/models/labels.txt
    - assets/models/yolov8/yolov8n_float32.tflite
    - assets/models/yolov8/labels.txt
